resources:

  repositories:
  - repository: self
    type: git

stages:
- stage: '_Build'
  jobs:
  - job: 'Job1'
    displayName: 1Job
    steps:
    - script: |
        '##vso[task.setvariable variable=TEST]SOMEVALUE'
    
    - script: |
        'echo $(TEST)' |
