resources:
  repositories:
  - repository: self
    type: git

stages:
- stage: Build
  jobs:
  - job:
    displayName: Bu ild
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'tar'
        tarCompression: 'none'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
