resources:

  repositories:
  - repository: self
    type: git
   
variables:
  appName: check-your-czech
  experimentalSlotName: exp
  adminEmail: 'petersemkin@gmail.com'
  subscription: Visual Studio Enterprise Subscription (a7b6f428-0ed2-4721-9548-d17c361d9b77)

stages:
- stage: Build
  jobs:
  - job: Job1
    displayName: 'Build, Test, Publish'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Enterprise Subscription (a7b6f428-0ed2-4721-9548-d17c361d9b77)'
        scriptLocation: 'inlineScript'
        inlineScript: 'echo hello'