resources:

  repositories:
  - repository: self
    type: git

stages:
- stage: '_Build'
  jobs:
  - job: 'Job1'
    displayName: Job
    steps:
    - script: |
        echo '##vso[task.setvariable variable=TEST]SOMEVALUE'
    
    - task: CmdLine@2
      condition: eq('${{ variables.TEST }}', SOMEVALUE)
      inputs:
        script: 'echo $(TEST)'

    - task: CmdLine@2
      condition: eq('${{ variables.TEST }}', ANOTHERVALUE)
      inputs:
        script: 'echo $(TEST)'
