resources:
  repositories:
  - repository: self
    type: git

stages:
- stage: '_Build'
  jobs:
  - job: 'Job1'
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'tar'
        tarCompression: 'none'
        archiveFile: te st
        replaceExistingArchive: true
