resources:

  repositories:
  - repository: self
    type: git

stages:
- stage: '_Build'
  jobs:
  - job: 'Job1'
    displayName: 1Job
    steps:

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: Visual Studio Enterprise Subscription (a7b6f428-0ed2-4721-9548-d17c361d9b77)
        resourceGroupName: check-your-czech
        location: North Europe
        csmFile: arm-template.json
