resources:

  repositories:
  - repository: self
    type: git

stages:
- stage: '_Build'
  jobs:
  - job: 'Job1'
    displayName: 1Job
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'tar'
        tarCompression: 'none'
        archiveFile: te st
        replaceExistingArchive: true

    - task: AzureResourceGroupDeployment@2
      displayName: Create Application Insights
      inputs:
        azureSubscription: $(subscription)
        resourceGroupName: $(appName)
        location: North Europe
        csmFile: arm-template.json
        overrideParameters: -appName $(appName) -adminEmail $(adminEmail)
        deploymentName: $(appName)