module WikiParsing.ConcreteArticles

open Common.WikiArticles

type AdjectiveArticleWithComparative = AdjectiveArticleWithComparative of AdjectiveArticle
type AdjectiveArticleWithPlural = AdjectiveArticleWithPlural of AdjectiveArticle
